# 配置RabbitMQ的基本信息  ip 端口 username  password..
spring:
  rabbitmq:
    #host: 192.168.23.129 # ip
    host: 127.0.0.1 # ip
    port: 5672
    username: heima
    password: heima
    virtual-host: /itcast
    publisher-confirms: true  # 开启发送确认
    publisher-returns: true   # 开启发送失败退回
    template:
      mandatory: true #配合 punisher-retrun使用

  #1. mandatory标志位
  #当mandatory标志位设置为true时，如果exchange根据自身类型和消息routeKey无法找到一个符合条件的queue，那么会调用basic.return方法将消息返还给生产者；当mandatory设为false时，出现上述情形broker会直接将消息扔掉。

  #2. immediate标志位
  #当immediate标志位设置为true时，如果exchange在将消息route到queue(s)时发现对应的queue上没有消费者，那么这条消息不会放入队列中。当与消息routeKey关联的所有queue(一个或多个)都没有消费者时，该消息会通过basic.return方法返还给生产者。

